enum PI_COMMANDS {
};

enum ESP_COMMANDS {
    ESP_CLIENT_INIT = 0,
    ESP_SERVER_INIT,
    ESP_SEND_DATA,
    ESP_WIFI_CONNECT,
    ESP_IS_CONNECTED,
    ESP_GET_CONNECTED_LIST,
    ESP_NOP,
    ESP_ACK,
};