# need the makefile to give an error if this doesn't exist
PROGS := server.c
COMMON_SRC := get-code.c

CFLAGS += -I..

# uncomment if you want it to automatically run.
# RUN=1

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = my-install

include $(CS140E_2023_PATH)/libpi/mk/Makefile.template
